// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ2d6iaZTO2XREB5cgweU6sEigxagJnw8',
    appId: '1:311270636271:web:07cecf5f0dfc2fe6f7b91a',
    messagingSenderId: '311270636271',
    projectId: 'buzzzchat-53a7e',
    authDomain: 'buzzzchat-53a7e.firebaseapp.com',
    storageBucket: 'buzzzchat-53a7e.firebasestorage.app',
    measurementId: 'G-Q1S71WKFV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYLa8xRaaUv26NufT6o59cE7z5wvHGDwM',
    appId: '1:311270636271:android:c952e394ef132440f7b91a',
    messagingSenderId: '311270636271',
    projectId: 'buzzzchat-53a7e',
    storageBucket: 'buzzzchat-53a7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFcE3VpsQ2_7zRIgSKhVqSzLs5MMwbkQo',
    appId: '1:311270636271:ios:55e3421ac19f6e22f7b91a',
    messagingSenderId: '311270636271',
    projectId: 'buzzzchat-53a7e',
    storageBucket: 'buzzzchat-53a7e.firebasestorage.app',
    iosBundleId: 'com.example.buzzzchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFcE3VpsQ2_7zRIgSKhVqSzLs5MMwbkQo',
    appId: '1:311270636271:ios:55e3421ac19f6e22f7b91a',
    messagingSenderId: '311270636271',
    projectId: 'buzzzchat-53a7e',
    storageBucket: 'buzzzchat-53a7e.firebasestorage.app',
    iosBundleId: 'com.example.buzzzchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ2d6iaZTO2XREB5cgweU6sEigxagJnw8',
    appId: '1:311270636271:web:f498804e9e873db8f7b91a',
    messagingSenderId: '311270636271',
    projectId: 'buzzzchat-53a7e',
    authDomain: 'buzzzchat-53a7e.firebaseapp.com',
    storageBucket: 'buzzzchat-53a7e.firebasestorage.app',
    measurementId: 'G-PJ17N8YNM7',
  );
}
